[tools]
flutter = "3.44.9"
java = "temurin-17"
zizmor = "latest"

[tasks]
"pub:get" = "flutter pub get"
"format:write" = "dart format ./"
"build:apk" = "flutter build apk --release"
"build:apk-split" = "flutter build apk --release --split-per-abi"
"lint:workflows" = "zizmor ./.github/workflows"

[tasks.format]
run = "dart format -o none --set-exit-if-changed ./lib ./test"
depends = ["pub:get"]

[tasks.analyze]
run = "flutter analyze --no-fatal-infos"
depends = ["pub:get"]

[tasks.test]
run = "flutter test"
depends = ["pub:get"]

[tasks.ci]
depends = ["format", "analyze", "test"]

[tasks.release]
depends = ["build:apk-split"]

[settings]
lockfile = true
