name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: https://github.com/dart-lang/setup-dart@v1
      - name: Set up Flutter
        uses: https://github.com/subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter pub get
      - name: Analyze
        run: dart analyze
      - name: Test
        run: flutter test
